In [133]:
from tensorflow.keras.models import Sequential
import pandas as pd 
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [134]:
df = pd.read_csv(r"C:\Users\Dell\Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [135]:
#No need of id in the dataset, so we have to delete this columns 
del df[df.columns[0]]# or by using slicing method also remove the specfic column => df = df.loc[:,'SepalLengthCm':] 
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [136]:
X = df.loc[:, df.columns[0:-1]]# we can use this => X = df.iloc[:,:-1]
y = df.loc[:,df.columns[-1]]# we can use this => y = df.iloc[:,-1:]
y.head()
X.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [137]:
output_classes = len(y.unique())
output_classes

3

In [138]:
X = df.loc[:, df.columns[0:-1]].values# convert into array 
y = df.loc[:,df.columns[-1]].values# convert into array 

In [139]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [141]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

print("Orginal shape of X: ", X.shape)
print("Orginal shape of y: ", y.shape)
print("shape of X_train: ", X_train.shape)
print("shape of X_test: ", X_test.shape)
print("shape of y_train: ", y_train.shape)
print("shape of y_test: ", y_test.shape)



Orginal shape of X:  (150, 4)
Orginal shape of y:  (150,)
shape of X_train:  (105, 4)
shape of X_test:  (45, 4)
shape of y_train:  (105,)
shape of y_test:  (45,)


In [142]:
print("Categorical conversion of y_train & y_test")
y_train = to_categorical(y_train, num_classes = output_classes, dtype ="uint8")
y_test = to_categorical(y_test,num_classes = output_classes, dtype ="uint8")


Categorical conversion of y_train & y_test


In [156]:
model = Sequential()
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=output_classes, activation='softmax'))

In [157]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [158]:
model.fit(X_train, y_train, epochs=150, batch_size=32)

Epoch 1/150
4/4 [==============================] - 0s 2ms/step - loss: 1.0099 - accuracy: 0.2762
Epoch 2/150
4/4 [==============================] - 0s 2ms/step - loss: 0.9209 - accuracy: 0.3429
Epoch 3/150
4/4 [==============================] - 0s 3ms/step - loss: 0.8663 - accuracy: 0.7048
Epoch 4/150
4/4 [==============================] - 0s 3ms/step - loss: 0.8254 - accuracy: 0.7143
Epoch 5/150
4/4 [==============================] - 0s 3ms/step - loss: 0.7920 - accuracy: 0.7143
Epoch 6/150
4/4 [==============================] - 0s 2ms/step - loss: 0.7589 - accuracy: 0.7143
Epoch 7/150
4/4 [==============================] - 0s 2ms/step - loss: 0.7284 - accuracy: 0.7143
Epoch 8/150
4/4 [==============================] - 0s 3ms/step - loss: 0.7056 - accuracy: 0.7524
Epoch 9/150
4/4 [==============================] - 0s 3ms/step - loss: 0.6812 - accuracy: 0.9238
Epoch 10/150
4/4 [==============================] - 0s 2ms/step - loss: 0.6614 - accuracy: 0.9048
Epoch 11/150
4/4 [===========

In [2]:
loss_and_metrics = model.evaluate(X_test, 
                                  y_test, 
                                  batch_size=128)

NameError: name 'model' is not defined

In [1]:
classes = model.predict(X_test, batch_size=128)
import numpy as np
print(classes.shape)
y_hat = np.max (classes,axis=0)


NameError: name 'model' is not defined

In [168]:
# Initializing Input vector
class_vector =[2, 2, 0, 1, 2, 2, 2, 1]
print(class_vector)
# Applying the function on input class vector
from tensorflow.keras.utils import to_categorical
output_matrix = to_categorical(class_vector, num_classes = 3, dtype ="int32")
print(output_matrix)

[2, 2, 0, 1, 2, 2, 2, 1]
[[0 0 1]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 1 0]]
